name: Build macOS DMG

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Enable corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build DMG
        env:
          BUILD_NUMBER: ${{ github.run_number }}
        run: yarn dist -c.buildVersion=$BUILD_NUMBER --publish never

      - uses: actions/upload-artifact@v4
        with:
          name: Diffier-dmg
          path: dist/*.dmg
